### ISSUE TITLE
The remote name could not be resolved: 'paper-api.alpaca.markets'

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#123]
I'm getting this error after running the example code (after making the switch to the ConnectAndAuthenticateAsync. Is this a known issue? I double checked the url I was using of course and it matches exactly with the example code

**Comment by OlegRa** [comment]
@ooples This DNS name is valid and it works fine on my side. In any case it's not an SDK issue - if OS unable to find some computer by DNS name top-level software can't help with this problem.

**Comment by ooples** [comment]
It isn't a connection issue on my side. I checked everything on my end and it works. I'm also receiving this error as well

A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied

**Comment by OlegRa** [comment]
Unfortunately, I'm unable to reproduce this problem on my side. Could you please provide more information about your environment: OS (exact version and bitness), .NET (exact flavor/version and bitness). Ideally, if you will provide full exception info or (in best case) full process dump collected at exception point it would be very helpful for investigation.

**Comment by ooples** [comment]
I'm using 64 bit windows 10 and .net 4.8

I believe I have narrowed down the source of the issue. If you place a breakpoint in the example code while the program is running then it seems to lose connection to the sock client when you continue running the program. I'm able to replicate it with my code on my end.

**Comment by ooples** [comment]
Digging further into this issue seems to point to the issue with the underlying socket losing connection for whatever reason but the existing api code makes it impossible to know when this happens. I suggest that you include the underlying socket's disconnected event in the api so the user can reconnect and authenticate once the socket is disconnected. You implement the connected event but not the disconnected event

**Comment by OlegRa** [comment]
OK. Sounds reasonable. Will try to include in upcoming 3.3.0 release.

**Comment by ooples** [comment]
I need to reopen this because I'm continuing to get this exception even after all of the changes. It seems to happen about as often as the other #274 issue so my best guess is that they are related.

Here is my exception info for this:

Exception Time:
19/01/2021 7:51:10 PM

Exception Type:
System.Net.Http.HttpRequestException

Exception Message:
An error occurred while sending the request.

Exception StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Alpaca.Markets.HttpClientExtensions.<sendThrottledAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Alpaca.Markets.HttpClientExtensions.<callAndDeserializeAsync>d__4`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Alpaca.Markets.HttpClientExtensions.<callAndDeserializeAsync>d__2`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at OoplesFinanceUserClient.AlpacaApi.<GetStocksOwnedInfo>d__35.MoveNext()

Exception Target Site:
Throw

Exception Source:
mscorlib

Inner Exception Message:
The remote name could not be resolved: 'paper-api.alpaca.markets'

Inner Exception StackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)

**Comment by OlegRa** [comment]
@ooples I'm not sure why do you want to re-open this one. The `Disconnected` event works as expected and has no relation with this particular DNS resolving the problem. See my comments for issue #274 - this is a low-level operating system error and SDK unable to do anything useful with it.
