### ISSUE TITLE
ListMinuteAggregatesAsync throwing Exception 'Unauthorized'

### ISSUE THREAD

**Issue by SavageShade** [alpacahq/alpaca-trade-api-csharp#136]
Over the last week I have been able to ListMinuteAggregatesAsync() to get Aggregate data with no problems. Today I am getting the following error when making that same call. Alpaca calls have been working for me today, seems to be something with Polygon? Might be related to #135?

`Exception has occurred: CLR/Alpaca.Markets.RestClientErrorException
An exception of type 'Alpaca.Markets.RestClientErrorException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'Unauthorized'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Newtonsoft.Json.JsonSerializationException : Required property 'code' not found in JSON. Path '', line 1, position 31.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(Object newObject, JsonReader reader, JsonObjectContract contract, Int32 initialDepth, JsonProperty property, PropertyPresence presence, Boolean setDefaultValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Alpaca.Markets.RestClient.<deserializeAsync>d__15`2.MoveNext()`

**Comment by OlegRa** [comment]
@SavageShade I can reproduce it only with paper-trading account. My staging account works fine. Which account do you use? If you use production account - send me information about your environment (OS/.NET versions/bitness) and minimal code snippet for reproducing this issue.

**Comment by SavageShade** [comment]
@OlegRa Thanks for the follow up on this. The problem is currently happening with my paper-trading account. I can try to use my production account later to see if my results match yours. Assuming I get the same results, would that mean Polygon is no longer allowing paper-trading accounts of Alpaca to connect to it's API or am I interpreting that or the issue wrong?

**Comment by OlegRa** [comment]
@SavageShade Yes, you got it right. I'll ask Alpaca guys about this issue. It's not clear from documentation but looks like historical data are also subject of Brokerage account contract.

**Comment by OlegRa** [comment]
I've checked it with production, stage and paper-only API keys. Historical data requests are working only for production and stage (development) environment. I'm still waiting confirmation from Alpaca and Polygon.io side but most probably it's true and this new rule was enforced by last back-end update. I'm unable to do anything with it from SDK side.
