### ISSUE TITLE
Error after update to 3.5.0-alpha4

### ISSUE THREAD

**Issue by thi517** [alpacahq/alpaca-trade-api-csharp#164]
I was working with 3.5.0-alpha3 then got error after update.

System.AggregateException: One or more errors occurred. ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Alpaca.Markets.RateThrottler.CheckHttpResponse(HttpResponseMessage response)
   at Alpaca.Markets.RestClient.<callAndDeserializeSingleObjectAsync>d__9`2.MoveNext()
   --- End of inner exception stack trace ---
   at Alpaca.Markets.RestClient.<callAndDeserializeSingleObjectAsync>d__9`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Alpaca.Markets.RestClient.<getObjectsListAsync>d__12`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Thi.Finance.TradingPaperOnly.<Run>d__4.MoveNext() in C:\Projects\thi\Thi.Finance\Alpaca\TradingPaperOnly.cs:line 30
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Thi.Finance.Program.<Main>d__0.MoveNext() in C:\Projects\thi\Thi.Finance\Program.cs:line 28
---> (Inner Exception #0) System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at Alpaca.Markets.RateThrottler.CheckHttpResponse(HttpResponseMessage response)
   at Alpaca.Markets.RestClient.<callAndDeserializeSingleObjectAsync>d__9`2.MoveNext()<---

**Comment by OlegRa** [comment]
@thi517 Could you please provide full exception stack and (ideally minimal code snippet for reproducing this problem)?

**Comment by DarioVonaesch** [comment]
I'm getting the same when just running the provided samples!.

**Comment by OlegRa** [comment]
@thi517 @SteveHaudegen Could you please, guys, check the latest version [3.5.0-beta2](https://www.nuget.org/packages/Alpaca.Markets/3.5.0-beta2) - it should work better (but don't forget - next trading day is Tuesday, January 21).

**Comment by SteveHaudegen** [comment]
Works now! Thank you for the swift fix!
