### ISSUE TITLE
URI Request too large

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#238]
I'm getting the following exception when running the following code:

Alpaca.Markets.RestClientErrorException
  HResult=0x80131500
  Message=Request-URI Too Large
  Source=Alpaca.Markets
  StackTrace:
   at Alpaca.Markets.HttpResponseMethodExtensions.<DeserializeAsync>d__0`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Alpaca.Markets.HttpResponseMethodExtensions.<DeserializeAsync>d__0`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Alpaca.Markets.HttpClientExtensions.<callAndDeserializeAsync>d__4`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Alpaca.Markets.HttpClientExtensions.<callAndDeserializeAsync>d__2`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Alpaca.Markets.HttpClientExtensions.<GetAsync>d__15`4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
JsonReaderException: Unexpected character encountered while parsing value: <. Path '', line 0, position 0.

var activeAssets = await alpacaTradingClient.ListAssetsAsync(new AssetsRequest() { AssetStatus = AssetStatus.Active });
var symbolsList = activeAssets.Select(x => x.Symbol).ToList();
var barSet = await alpacaDataClient.GetBarSetAsync(new BarSetRequest(symbolsList, TimeFrame.Minute) { Limit = 20 });

I'm assuming the error is happening because the requested symbols list is too large and if that is the case then there should be a check added to see if the requested symbols list has too many items and pass that error on to the user

**Comment by OlegRa** [comment]
@ooples Please, test it using the latest version [3.9.0-rc1](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v3.9.0-rc1) and close if the problem is fixed (client-side exception thrown without any REST calls).

**Comment by ooples** [comment]
It works as expected now. Quick question, do you know the max requests you are allowed to make using the api?

**Comment by OlegRa** [comment]
@ooples I don't know the exact values for per/minute or per/day request limits. I think you can ask Alpaca support (on the forum for example).
