### ISSUE TITLE
Bracket Order BUY with Limit type instead of Market

### ISSUE THREAD

**Issue by citestaccount** [alpacahq/alpaca-trade-api-csharp#259]
When trying to buy using Bracket order , instead of doing Market order on BUY trying to do Limit, order type I get an error. is that excepted?
I have verified that orderDto.BuyPrice has value and if I change  LimitOrder.Buy to MarketOrder.Buy it works

```    
    var order = await AlpacaTradingClientStrategy.GetAlpacaTradingClient().PostOrderAsync(
              LimitOrder.Buy(orderDto.Symbol, orderDto.Quantity, orderDto.BuyPrice)
                  .WithDuration(TimeInForce.Gtc)
                  .Bracket(
                      stopLossStopPrice: orderDto.BuyPrice * orderDto.StopLossPricePercent,
                      takeProfitLimitPrice: orderDto.BuyPrice * orderDto.TakeProfitLimitPricePercent
                  ));
```
```
Alpaca.Markets.RestClientErrorException: limit orders require a limit price
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken, IThrottler throttler)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson,TContent](HttpClient httpClient, HttpMethod method, Uri endpointUri, TContent content, CancellationToken cancellationToken, IThrottler throttler)
```

**Comment by citestaccount** [comment]
when doing via postman this order is valid

```
{
  "side": "buy",
  "symbol": "SPY",
  "type": "limit",
  "qty": "100",
  "limit_price": "325",
  "time_in_force": "gtc",
  "order_class": "bracket",
  "take_profit": {
    "limit_price": "350"
  },
  "stop_loss": {
    "stop_price": "299"    
  }
}
```

**Comment by OlegRa** [comment]
This one is a duplicate for issue #258 but I will not close it because it would be better to test it separately.

**Comment by OlegRa** [comment]
@citestaccount You can test the fix in the version [3.9.1](https://github.com/alpacahq/alpaca-trade-api-csharp/releases/tag/v3.9.1) already available on the NuGet.

**Comment by citestaccount** [comment]
Thanks for the quick fix, will test it tomorrow and let you know @OlegRa

**Comment by citestaccount** [comment]
this works Thanks!!
