### ISSUE TITLE
System.Net.Http.HttpRequestException: The request was aborted: Could not create SSL/TLS secure channel.

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#278]
Latest version is producing the following error for users that run my code on older operating systems.

```
Exception Type:
System.Net.Http.HttpRequestException

Exception Message:
An error occurred while sending the request.

Exception StackTrace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at System.Net.Http.HttpClient.<FinishSendAsyncUnbuffered>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Alpaca.Markets.HttpClientExtensions.<sendThrottledAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Alpaca.Markets.HttpClientExtensions.<callAndDeserializeAsync>d__4`2.MoveNe
xt()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at Alpaca.Markets.HttpClientExtensions.<callAndDeserializeAsync>d__2`2.MoveNe
xt()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot
ification(Task task)
   at OoplesFinanceUserClient.AlpacaApi.<InitializeEverything>d__33.MoveNext() i
n C:\Users\cheat\source\repos\OoplesFinanceUserClient\AlpacaApi.cs:line 519

Exception Target Site:
Throw

Exception Source:
mscorlib

Inner Exception Message:
The request was aborted: Could not create SSL/TLS secure channel.

Inner Exception StackTrace:
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
```

I found this on stacktrace that possibly fixes the issue:
https://stackoverflow.com/questions/2859790/the-request-was-aborted-could-not-create-ssl-tls-secure-channel

This happens when I call GetAccountAsync and I'm using 5.0 alpha 2

**Comment by OlegRa** [comment]
@ooples Could you please re-test this issue using the latest alpha version of SDK?

**Comment by ooples** [comment]
Alright it is running now on Windows 7 with this version. There seems to be a new error though caused by this new version and I will create an issue for it
