### ISSUE TITLE
Auto Reconnect Stuck In Loop

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#297]
This is related to issue #274 and issue #281 but I have noticed that if you get one of those errors, the reconnect will work as expected but I get one of the two below error messages and it will get stuck in a loop until it reaches the max reconnection limit. 

"your connection is rejected while another connection is open under the same account"
"The socket is connected, you needn't connect again!"

I think the best method would be to implement the polly library and handle this on the back end but I wanted to go ahead and report this issue to you

**Comment by OlegRa** [comment]
@ooples You are right, it looks like a bug and I'll try to figure out how this situation can be handled in reconnection wrapper. Most probably the server-side socket is re-used with the full state (connected and authenticated) but I'm not sure we can obtain this information from the underlying web socket component. Unfortunately, the Polly library will not help here - it most designed for request/response interactions handling not for streaming issues resolving.

**Comment by OlegRa** [comment]
@ooples Please, test the latest changes in 5.0.2-alpha1 - you need both SDK and Extensions package updated.

**Comment by ooples** [comment]
I will test out these new changes and let you know

**Comment by ooples** [comment]
Will the new changes address these errors I sometimes get as well?

Exception #1:
Exception Message:
Unable to read data from the transport connection: An established connection was aborted by the software in your host machine..

Exception StackTrace:
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.ReadAsync()

Exception Target Site:
ThrowException

Exception Source:
System.Net.Sockets

Inner Exception Message:
An established connection was aborted by the software in your host machine.

Exception #2:
Alpaca data streaming client error:
Exception Type:
System.Exception

Exception Message:
HTTP/1.1 404 Not Found

**Comment by ooples** [comment]
After updating everything to the latest version, I notice much less exceptions but I'm still getting caught in a loop but only with these exceptions so far as I can see:

We are waiting for the market to open...
Market opened.
Alpaca streaming client socket opened.
Alpaca streaming client connection status is Authorized.
Alpaca data streaming client socket opened.
Alpaca data streaming client connection status is Unauthorized.
Alpaca data streaming client error:
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
auth failed

Alpaca data streaming client connection status is Unauthorized.
Alpaca data streaming client error:
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
not authenticated

Alpaca data streaming client connection status is Unauthorized.
Alpaca data streaming client error:
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
auth timeout

Alpaca data streaming client socket opened.
Alpaca data streaming client connection status is Unauthorized.
Alpaca data streaming client error:
Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
auth failed

**Comment by OlegRa** [comment]
@ooples Please, try the 5.0.2-alpha2 version of both packages.

**Comment by ooples** [comment]
I'm going to try the new versions but I forgot to report that I'm now getting sporadic errors for the following exception and then followed up the below exception:

Exception Type:
System.IO.IOException

Exception Message:
 Received an unexpected EOF or 0 bytes from the transport stream.

Exception StackTrace:
   at System.Net.Security.SslStream.FillBufferAsync[TIOAdapter](TIOAdapter adapter, Int32 numBytesRequired)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.Net.Http.HttpConnection.FillAsync(Boolean async)
   at System.Net.Http.HttpConnection.Fill()
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer(Span`1 userBuffer, Boolean& readToUserBuffer)
   at System.IO.StreamReader.ReadSpan(Span`1 buffer)
   at System.IO.StreamReader.Read(Char[] buffer, Int32 index, Int32 count)
   at Newtonsoft.Json.JsonTextReader.ReadData(Boolean append, Int32 charsRequired)
   at Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(Char quote)
   at Newtonsoft.Json.JsonTextReader.ParseString(Char quote, ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken, IThrottler throttler)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken, IThrottler throttler)
   at OoplesFinanceUserClient.AlpacaApi.GetStocksOwnedInfo() in D:\Code Projects\OoplesFinanceUserClient\AlpacaApi.cs:line 1367

Exception Target Site:
MoveNext

Exception Source:
System.Net.Security

Alpaca streaming client error:
Exception Type:
System.Net.Sockets.SocketException

Exception Message:
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.

**Comment by ooples** [comment]
This issue seems to be fixed with the latest version but it seems to have caused a different issue which I have reported
