### ISSUE TITLE
Not Found exception thrown in GetLastQuoteAsync method

### ISSUE THREAD

**Issue by woaksie** [alpacahq/alpaca-trade-api-csharp#300]
This code throws an exception for the symbol XITK. Other symbols work fine.

```cs
_dataClient = Environments.Paper.GetAlpacaDataClient(securityKey);
return await _dataClient.GetLastQuoteAsync(symb).ConfigureAwait(true);
```

```cs
System.AggregateException: One or more errors occurred. (GetQoute() for XITK failed)
 ---> System.Exception: GetQoute() for XITK failed
 ---> Alpaca.Markets.RestClientErrorException: Not Found
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken, IThrottler throttler)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken, IThrottler throttler)
   at TestingAlpaca.AlpacaGateway.GetQuote(String symb) in D:\Projects\TestingAlpaca\AlpacaGateway.cs:line 609
   --- End of inner exception stack trace ---
   at TestingAlpaca.AlpacaGateway.GetQuote(String symb) in D:\Projects\TestingAlpaca\AlpacaGateway.cs:line 609
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at TestingAlpaca.TriStocker.Runner.GetLatestData(AlpacaGateway ap, TopDog dog, Boolean tryToBuy) in D:\Projects\TestingAlpaca\TriStocker\Runner.cs:line 313
```

Acording to Alpaca XITK is:

XITK is tradable? True, status Active, class UsEquity, easy to borrow False, shortable False, marginable True, exchange Arca

**Comment by OlegRa** [comment]
@woaksie It's not a client-side issue and cannot be resolved by SDK. Even if you'll make the last quote HTTP request using Postman or curl you get the same result. Most probably root cause is the market coverage of Alpaca Data v1 API. I'm not sure Arca is included in [this list](https://alpaca.markets/docs/api-documentation/api-v2/market-data/alpaca-data-api-v1/). I think it's better to ask this question using usual Alpaca support channels (forum, Slack, or email). Just formulate it in an SDK-independent way - ask about the XITK symbol availability in the Alpaca Data API v1 (not v2).
