### ISSUE TITLE
Error converting value "APPROVED" to type 'Alpaca.Markets.AccountStatus'

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#329]
Getting this error after updating to the latest version

```cs
Exception Message:
Error converting value "APPROVED" to type 'Alpaca.Markets.AccountStatus'. Path 'status', line 1, position 96.

Exception StackTrace:
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.AlpacaApi.RunBuyOrderProcess(List`1 topStocksList) in D:\Code Projects\OoplesFinanceAdminClient\AlpacaApi.cs:line 858

Exception Target Site:
ReadJson

Exception Source:
Newtonsoft.Json
```

**Comment by ooples** [comment]
@OlegRa Why is this labeled as an enhancement? Wouldn't it be classified as a bug?

**Comment by OlegRa** [comment]
For me, it's not an error - this account status (and many others) not documented [here](https://alpaca.markets/docs/api-documentation/api-v2/account/) in the official Alpaca documentation. So I'll just apply a workaround for not throw an exception in this case but it's definitely not an SDK error - maybe it's an Alpaca documentation error :)
