### ISSUE TITLE
Error: Account is Not Authorized to Trade

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#330]
I'm also getting this strange error after updating to the latest version without changing anything in my code

Exception Message:
account is not authorized to trade

Exception StackTrace:
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson,TContent](HttpClient httpClient, HttpMethod method, Uri endpointUri, TContent content, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.AlpacaApi.SubmitOrder(String symbol, String market, Decimal quantity, Decimal currentPrice, OrderSide side, OrderType type, TimeInForce orderDuration, IAsset assetInfo, Decimal limitPrice, Decimal stopPrice, Boolean useExtendedHours, Nullable`1 orderClass, Decimal takeProfitLimitPrice, Decimal stopLossLimitPrice, Decimal stopLossStopPrice, Nullable`1 trailOffset, String clientOrderID) in D:\Code Projects\OoplesFinanceAdminClient\AlpacaApi.cs:line 1968

Exception Target Site:
MoveNext

Exception Source:
Alpaca.Markets

Exception Type:
Alpaca.Markets.RestClientErrorException

**Comment by OlegRa** [comment]
@ooples It's not an SDK problem - this message is extracted from the error message received from the server. Most probably your account is not active or a trading limited for some reason. Ask Alpaca support about it. Moreover, in forums, you can find many similar cases, and in most of them, the root cause is the account state.

**Comment by ooples** [comment]
Yeah I assumed it was but since I didn't change anything other than update to the new version I figured I would post it just in case. The alpaca team apparently messed up something with older accounts before their switch to v2 and now older accounts will sometimes get this error message when doing a reset on their portfolio. Just for anyone's future reference
