### ISSUE TITLE
CancellationTokenSource has been disposed exception

### ISSUE THREAD

**Issue by JCloarec** [alpacahq/alpaca-trade-api-csharp#392]
Hi, I used the client in a test console project and everything was running fine.

However, I'm now using the client in a custom library, using the client as such:

```cs
var tradingClient = Environments.Paper.GetAlpacaTradingClient(key);
var assets = m_TradingClient.ListAssetsAsync(new AssetsRequest()).Result;
```

But I'm getting a "The CancellationTokenSource has been disposed." exception when calling ListAssetsAsync. I got the following stack trace:

```cs
at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at System.Threading.CancellationTokenSource.InternalRegister(Action`1 callback, Object stateForCallback, SynchronizationContext targetSyncContext, ExecutionContext executionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state, Boolean useSynchronizationContext, Boolean useExecutionContext)
   at System.Threading.CancellationToken.Register(Action`1 callback, Object state)
   at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__109.MoveNext()
```

Do you have an idea as to why this is happening?

**Comment by OlegRa** [comment]
@JCloarec Looks like a bug for me :( I'll take a look at it. Could you please tell me what version of SDK do you use, what is your target .NET version, and what is your OS version/bitness (most probably Windows 10 but I want to know the exact version)?

**Comment by JCloarec** [comment]
It's fixed, working fine now! Thanks a lot
