### ISSUE TITLE
Exception: No Such Host

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#407]
I started getting this error fairly often after updating to the latest version so I wanted to bring it to your attention

```cs
Exception Type:
System.Net.Sockets.SocketException

Exception Message:
No such host is known.

Exception StackTrace:
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at Polly.Utilities.ExceptionExtensions.RethrowWithOriginalStackTraceIfDiffersFrom(Exception exceptionPossiblyToThrow, Exception exceptionToCompare)
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Polly.Wrap.AsyncPolicyWrapEngine.ImplementationAsync[TResult](Func`3 func, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext, IAsyncPolicy outerPolicy, IAsyncPolicy`1 innerPolicy)
   at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at Alpaca.Markets.ThrottleParameters.CustomHttpHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpMessageInvoker httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.AlpacaApi.GetStockOwnedInfo(List`1 closedOrdersList, List`1 openOrdersList, StockData marketDataClass, IPosition position, DateTime date, String symbol) in D:\Code Projects\OoplesFinanceAdminClient\AlpacaApi.cs:line 1983
```

**Comment by OlegRa** [comment]
@ooples Please, share a small code snippet for reproducing the issue and the exact package version. If you'll use the pre-defined issues templates (bug report in this case) it would be also very helpful.

**Comment by ooples** [comment]
I'm getting this at the line below and using the very latest which I believe is 6.0.1 Alpha 3

var asset = !string.IsNullOrEmpty(symbol) ? await alpacaTradingClient.GetAssetAsync(symbol).ConfigureAwait(false) : null;

**Comment by OlegRa** [comment]
@ooples It sounds strange but I'm unable to reproduce this issue on my side. I've tried both paper and live environments and all works fine - all endpoints that should return data at this time work as expected.

**Comment by ooples** [comment]
That is very strange. For more information I'm getting this error
consistently on some portfolios but not others so my guess is that it is
related to certain symbols. Can you do anything on your end to handle this
exception like add it to the ignored messages and/or reconnection logic?

**Comment by OlegRa** [comment]
I'm not sure it's a good idea to add such an error into the list of default socket errors for reconnection. In most cases, this error is a signal of serious problems with DNS resolution (and probably other low-level network problems). You can always modify throttle parameters for a particular client via configuration. Just add the required socket error code into the `RetrySocketErrorCodes` collection before instantiating the client.
