### ISSUE TITLE
"Fill" order status enum not present

### ISSUE THREAD

**Issue by ttt733** [alpacahq/alpaca-trade-api-csharp#45]
As reported by a user on Slack:

```
I download Alpaca.Markets and run the test OrderActionsTest in Alpca,Markets.Tests, I got the following error: Newtonsoft.Json.JsonSerializationException
 HResult=0x80131500
 Message=Error converting value "fill" to type 'Alpaca.Markets.OrderStatus'. Path 'data.event', line 1, position 48.
 Source=Newtonsoft.Json
 StackTrace:
  at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
  at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
  at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
  at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
  at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
  at Newtonsoft.Json.Linq.JToken.ToObject[T]()
  at Alpaca.Markets.SockClient.handleDataReceived(Object sender, DataReceivedEventArgs e) in C:\Users\chu\OneDrive\Alpaca\alpaca-trade-api-csharp-master\alpaca-trade-api-csharp-master\Alpaca.Markets\SockClient.cs:line 170
  at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
  at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.<ReadAsync>d__12.MoveNext()

Inner Exception 1:
ArgumentException: Requested value 'fill' was not found.
```
The enum value here should be fixed.

**Comment by OlegRa** [comment]
@ttt733 Please, test using latest [2.1.4](https://www.nuget.org/packages/Alpaca.Markets/2.1.4) version of NuGet package and close it if problem was solved.
