### ISSUE TITLE
[BUG]: AuthenticationException: Authentication failed because the remote party sent a TLS alert: 'IllegalParameter'.

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#454]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Trying to help out with a windows forms project and have attached a screenshot showing the error that I have never seen before
![alpaca_http_exception](https://user-images.githubusercontent.com/3075685/154298577-45597ee4-1a8e-4755-be26-30beb0891c72.png)

### Expected Behavior

With valid API info should be authenticating correctly

### Steps To Reproduce

I have attached the full method code below. This is where the error is coming from:

```cs
public static async Task<IReadOnlyList<IBar>> DownloadHistoricalBars(HistoricalBarsRequest histRequest)
{
    var client = Environments.Paper.GetAlpacaDataClient(new SecretKey(GetAlpacaPaperPublicKeyAPI(), GetAlpacaPaperSecretKeyAPI()));
    var result = await client.ListHistoricalBarsAsync(histRequest).ConfigureAwait(false);

    return result.Items;
}
```

### Environment

Using .net 6 with Alpaca.Markets 5.2.8

**Comment by OlegRa** [comment]
@ooples I've tested this code on Windows 10 x64 PC using WinForms projects with .NET 6.0, .NET 5.0, and .NET Framework 4.8 runtimes and it works as expected on all these targets. Moreover, such integration tests work fine on GitHub CI/CD each week so I'm pretty sure the problem is not in SDK itself but in the development PC (OS/.NET/settings/etc.)

What are your exact build and run configuration that causes this problem? For proper reproducing I need the next information:

- Operating system exact version and bitness. I assume that it's 64-bit Windows 10 but the exact version number produced by the `ver` command is required. On my side, this command returns the `Microsoft Windows [Version 10.0.19044.1526]` string.
- That is your target framework and bitness of your application. According to your initial post, it's .NET 6.0 with (most probably) `Any CPU` target but if you'll be able to get the exact version number of CLR used for running your app it would be very helpful. The `RuntimeInformation.FrameworkDescription` property returns all required information about the runtime.

And the last question - do you able to connect the Alpaca API using the SDK on the same box if you use the console application with the same target framework?

**Comment by ooples** [comment]
@OlegRa I would tend to agree with you. I have dug further into the code and think this might be a strange side effect from a connection possibly. The code I'm helping out with doesn't use the reconnection logic and I remember seeing strange exceptions like this. That being said I'm not 100% sure so here is my info below:

Microsoft Windows [Version 10.0.22000.526] 64 bit
.NET 6.0.2
Yes I'm connecting using the sdk on the same box for both apps

**Comment by OlegRa** [comment]
@ooples According to a version number, it's a Windows 11 beta version from Insider Preview ring. The problem root cause can be even in low-level network drivers or OS components not in .NET itself. Just to be clear - this exception is not that you experience for EVERY call in SDK - just for historical data endpoints, right?

**Comment by OlegRa** [comment]
Sounds very strange - all connections share the same code for handling requests/responses. I see that Alpaca updated their SSL certificate for the `data.alpaca.markets` domain - maybe it will help to solve this issue. In any case, it looks like a low-level problem with certificates and I'm not sure how we can fix it at the SDK level. I'll try to install this Windows version on VM this weekend and try to reproduce this problem on my side.

**Comment by OlegRa** [comment]
@ooples I've tried to reproduce this problem on VM with the same version of Windows/.NET installed but with no success. All requests work fine and I don't see any Win32/SSL errors. Could you please send me the next data:

- Full exception information in text form. I want to track the exception throw place in the .NET sources but I need a full stack trace for this job. You can press the `Copy details` button in VS and paste the clipboard here - it would be enough.
- Minimal code example for reproducing the problem. Not just one method but a full project with code and all build/run options. AFAIU even the code from the README page should fail but maybe some project settings affect the result on your side.
- Full process memory dump collected at the moment of exception throwing. You should enable exception intercepting at throw place in VS and save full dump at the place there such exception will throw. Please, do it not for an original app but for a demo app.

The Win32 exceptions look strange for me - if your target framework is .NET 6 your HTTP handler should be fully managed. The `WinHttpHandler` that can produce such error should be used only if you target Windows-specific .NET Framework.

**Comment by ooples** [comment]
@OlegRa I went ahead and completely rebuilt the .net app using .net 6 because you were correct. The original app was built using .net framework and ported over to .net 6. Now I'm getting a constant new error and this project barely has any code in it so I know it isn't anything caused by the software. Right now all I'm doing is connecting to alpaca and utilizing a stream just like in my personal software.

System.Net.WebSockets.WebSocketException: 'The server returned status code '429' when status code '101' was expected.'

Full stacktrace:

   at System.Net.WebSockets.WebSocketHandle.<ConnectAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at System.Net.WebSockets.ClientWebSocket.<ConnectAsyncCore>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Alpaca.Markets.WebSocketsTransport.<StartAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Alpaca.Markets.StreamingClientBase`1.<ConnectAndAuthenticateAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at ProjectPhoenix.FormDashboard.<InitializeAlpaca>d__1.MoveNext() in F:\repos\ProjectPhoenix\UI\Forms\FormDashboard.cs:line 65
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at ProjectPhoenix.FormDashboard..ctor() in F:\repos\ProjectPhoenix\UI\Forms\FormDashboard.cs:line 18
   at ProjectPhoenix.Program.Main() in F:\repos\ProjectPhoenix\Program.cs:line 14

**Comment by OlegRa** [comment]
The [429 HTTP status](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) in the case of the Alpaca streaming client means one simple thing - you already have an active and authorized connection to this stream and any new connection attempts are not possible. Ideally, you should receive the appropriate error at the application layer but Alpaca also filters/blocks connections by IP (at transport layer). Just check that your application opens only a single connection to each Alpaca stream and you don't have any connections to the same stream from the same IP with the same credentials (secret ID/key pair).

**Comment by ooples** [comment]
I contacted alpaca and apparently it was a server side issue with my account so I'm closing this
