### ISSUE TITLE
[BUG]: Reconnection isn't working in certain circumstances

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#517]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Pasting my issues from the other issue

I'm testing the brand new changes but there is a serious issue I'm noticing. I simulated internet going down by restarting my ethernet adapter but with this latest version, the sockets get closed after erroring out which is expected but there seems to be no attempts at reopening the connection. I haven't changed my reconnection logic at all and only related change was to override the new timeout setting

One strange thing I'm noticing is that Alpaca.Markets is 6.0.4-beta 1 and Alpaca.Markets.Extensions is 6.0.3 and I believe reconnection logic is handled using Extensions. Could mean nothing of course

### Steps To Reproduce

I'm able to replicate this by disabling the ethernet adapter and then enabling it again. Socket stays closed and doesn't attempt to reconnect. However when running the same code without messing with the ethernet adapter, I can see that it does attempt to reconnect on its own.

### Environment

- SDK Version: 6.0.4-beta1
- OS (version, bitness): Windows 10
- .NET SDK (version): .net 6
- target process .NET version/bitness: 64 bit

**Comment by OlegRa** [comment]
@ooples If you will provide logs with stack traces for exceptions reported via the OnError event (as you've made for #499) it would be very helpful. Most probably the changed behavior is related to these changes but I'm not sure how to keep the previous fix and still reconnect in case of the disabled network.

**Comment by ooples** [comment]
@OlegRa I just disabled my ethernet adapter again and here is the full stacktrace I'm getting. 

```
Alpaca streaming client error: Unable to connect to the remote server
Exception Type:
System.Net.WebSockets.WebSocketException

Exception Message:
Unable to connect to the remote server

Exception StackTrace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.StartAsync(CancellationToken cancellationToken)

Exception Target Site:
MoveNext

Exception Source:
System.Net.WebSockets.Client

No such host is known. (paper-api.alpaca.markets:443)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)

No such host is known.

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

Alpaca streaming client socket closed.
Alpaca data streaming client error: Unable to connect to the remote server
Exception Type:
System.Net.WebSockets.WebSocketException

Exception Message:
Unable to connect to the remote server

Exception StackTrace:
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)
   at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, CancellationToken cancellationToken)
   at Alpaca.Markets.WebSocketsTransport.StartAsync(CancellationToken cancellationToken)

Exception Target Site:
MoveNext

Exception Source:
System.Net.WebSockets.Client

No such host is known. (stream.data.alpaca.markets:443)

   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, CancellationToken cancellationToken, ClientWebSocketOptions options)

No such host is known.

   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)

Alpaca data streaming client socket closed.
```

**Comment by ooples** [comment]
@OlegRa One suggestion I would have from my own personal programming is where I use a Polly wait and retry policy and put a while loop inside that doesn't exit the loop while the internet is down. This way I put a temporary pause on all of my work until the internet is back for any process that relies on the internet to succeed. Not a very elegant solution I suppose but it has worked wonders for me

**Comment by OlegRa** [comment]
@ooples Please, try the [6.0.4-beta1](../releases/tag/ext-6.0.4-beta1) version of the Extensions package and check if the problem is solved.
