### ISSUE TITLE
Add the new order statuses

### ISSUE THREAD

**Issue by OlegRa** [alpacahq/alpaca-trade-api-csharp#592]
There are some new order statuses that are already supported by other SDKs:

- `accepted`
- `held`
- `pending_review`

The .NET SDK should support them as well (including 5.x LTS release)

**Comment by ooples** [comment]
I figured this was related but I got a few of these errors today:

```
Alpaca streaming client error: Error converting value "accepted" to type 'Alpaca.Markets.TradeEvent'. Path 'data.event', line 1, position 52.
Exception Type:
Newtonsoft.Json.JsonSerializationException

Exception Message:
Error converting value "accepted" to type 'Alpaca.Markets.TradeEvent'. Path 'data.event', line 1, position 52.

Exception StackTrace:
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   at Alpaca.Markets.ActionExtensions.DeserializeAndInvoke[TApi,TJson](Action`1 eventHandler, JToken eventArg)
   at Alpaca.Markets.AlpacaStreamingClient.handleTradeUpdate(JToken token)
   at Alpaca.Markets.SynchronizationQueue.processingTask()

Exception Target Site:
ReadJson

Exception Source:
Newtonsoft.Json

Exception HResult:
-2146233088

Requested value 'accepted' was not found.

   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
```

**Comment by OlegRa** [comment]
I've updated the 7.x version with the latest changes too so now these new order statuses should be available even for users who prefer to use pre-release versions of SDK from NuGet.
