### ISSUE TITLE
[BUG]: Endpoint not found

### ISSUE THREAD

**Issue by ooples** [alpacahq/alpaca-trade-api-csharp#594]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Exception Type:
Alpaca.Markets.RestClientErrorException

Exception Message:
endpoint not found

Exception StackTrace:
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at Alpaca.Markets.DataHistoricalClientBase`4.listHistoricalBarsAsync(THistoricalBarsRequest request, CancellationToken cancellationToken)
   at OoplesFinanceAdminClient.Helpers.AlpacaHelper.GetDailyHistoricalBars(String symbol, String market, DateTime startDate, DateTime endDate, BarTimeFrame barTf) in C:\Users\yolan\source\repos\ooples\OoplesFinanceAdminClient\Helpers\AlpacaHelper.cs:line 110

Exception Target Site:
MoveNext

Exception Source:
Alpaca.Markets

Exception HResult:
-2146233088

### Steps To Reproduce

```markdown
I received this error after switching to the latest version. I'm not sure if I'm missing something obvious but haven't changed anything on my end
```

### Environment

```markdown
- SDK Version: 7.0 alpha 1
- OS (version, bitness): 11
- .NET SDK (version): 7
- target process .NET version/bitness: 64bit
```

**Comment by OlegRa** [comment]
@ooples Could you please provide the exact API call that causes this error? Most of the top-level calls are inlined by default so it's not easy to understand which client you use. If you use crypto historical data maybe it would be better to revert back to the 6.x version of SDK for now. I'm not sure about the next 7.x release date for now.

**Comment by ooples** [comment]
@OlegRa I used the alpaca data client with the list historical bars method and I will go ahead and switch back to 6.x

**Comment by OlegRa** [comment]
@ooples I've updated the 7.x version with the latest changes so you can test it using this pre-release version and close.

**Comment by ooples** [comment]
@OlegRa ok I will test it out and let you know
