### ISSUE TITLE
Why does IAlpacaTradingClient implementation fail when using a simple http handler?

### ISSUE THREAD

**Issue by rudeGit** [alpacahq/alpaca-trade-api-csharp#616]
1. Setup a symbol with one or more orders. Say for example, for symbol 'SPXL', there are 2 orders.
2. I am using 6.1.12 version of Alpaca.Markets nuget package.
3. Using .net7.0 runtime.
4. Using windows 11 desktop computer

The following code path 1 returns the expected order count:

```c#
// See https://aka.ms/new-console-template for more information
using Alpaca.Markets;
using Alpaca.Markets.Extensions;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Threading;
using TestAlpaca;

//Paper trading keys
const string KEY_ID = "PKWX628F7ABWGYLYAC58";
const string SECRET_KEY = "VMkQdb2bdl6QihJlfQkmgjSHQSaqwEq8q2dgclFm";

//Code path 1
//var client = Environments.Paper.GetAlpacaTradingClient(new SecretKey(KEY_ID, SECRET_KEY));

//Code path 2
var tradingClientConfig = new AlpacaTradingClientConfiguration()
{
    HttpClient = new HttpClient(new MyAlpacaClientHandler()),
    SecurityId = new SecretKey(KEY_ID, SECRET_KEY),
    ApiEndpoint = Environments.Paper.AlpacaTradingApi
};
var client = tradingClientConfig.GetClient();

var symbol = "SPXL";

var request = new ListOrdersRequest()
{
    OrderStatusFilter = OrderStatusFilter.Closed,
    LimitOrderNumber = 25,
    OrderListSorting = SortDirection.Descending,
};
request = request.WithSymbol(symbol);

try
{
    var orders = await client.ListOrdersAsync(request);
    Console.WriteLine($"Number of orders: {orders.Count}.");
}
catch (Exception ex)
{
    Console.ForegroundColor = ConsoleColor.Red;
    Console.WriteLine($"Error: {ex}.");
}

Console.ReadLine();

``` 

It works as expected.

Now comment out the code path 1 and uncomment the code path 2 as shown below:

```c#
//Code path 1
//var client = Environments.Paper.GetAlpacaTradingClient(new SecretKey(KEY_ID, SECRET_KEY));

//Code path 2
var tradingClientConfig = new AlpacaTradingClientConfiguration()
{
    HttpClient = new HttpClient(new MyAlpacaClientHandler()),
    SecurityId = new SecretKey(KEY_ID, SECRET_KEY),
    ApiEndpoint = Environments.Paper.AlpacaTradingApi
};
var client = tradingClientConfig.GetClient();
```

and the following class and try again:

```c#
using System.Net.Sockets;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace TestAlpaca
{
    public class MyAlpacaClientHandler : HttpClientHandler
    {
        public MyAlpacaClientHandler()
        {
        }                

        protected override async Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
        {
            var response =  await base.SendAsync(request, cancellationToken);
            return response;
        }
    }
}
```
 The above http handler is as simple as it can be. **However it throws following error:**

```
Error: Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: ▼. Path '', line 0, position 0.
   at Newtonsoft.Json.JsonTextReader.ParseValue()
   at Newtonsoft.Json.JsonTextReader.Read()
   at Newtonsoft.Json.JsonReader.ReadAndMoveToContent()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize[T](JsonReader reader)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpResponseMethodExtensions.DeserializeAsync[TApi,TJson](HttpResponseMessage response)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpRequestMessage request, CancellationToken cancellationToken)
   at Alpaca.Markets.HttpClientExtensions.callAndDeserializeAsync[TApi,TJson](HttpClient httpClient, HttpMethod method, Uri endpointUri, CancellationToken cancellationToken)
   at Alpaca.Markets.AlpacaTradingClient.ListOrdersAsync(ListOrdersRequest request, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Projects\TestAlpaca\TestAlpaca\Program.cs:line 37.
```

**Any idea as to what is going on here? Is this a bug?**

**Comment by rudeGit** [comment]
I noticed that following response header is set:

```
Content-Encoding: gzip
```

Once I changed the code from following:

```c#
var tradingClientConfig = new AlpacaTradingClientConfiguration()
{
    HttpClient = new HttpClient(new MyAlpacaClientHandler()),
    SecurityId = new SecretKey(KEY_ID, SECRET_KEY),
    ApiEndpoint = Environments.Paper.AlpacaTradingApi
};
```

to following:

```c#
var tradingClientConfig = new AlpacaTradingClientConfiguration()
{
    HttpClient = new HttpClient(new MyAlpacaClientHandler() { AutomaticDecompression = System.Net.DecompressionMethods.All }),
    SecurityId = new SecretKey(KEY_ID, SECRET_KEY),
    ApiEndpoint = Environments.Paper.AlpacaTradingApi
};
```

It started working again !!!

**Comment by OlegRa** [comment]
@rudeGit Just a side note - you can wrap the default handler with your own using the feature added in the latest version. See the example [here](https://github.com/alpacahq/alpaca-trade-api-csharp/issues/605#issuecomment-1514934878).
