### ISSUE TITLE
[BUG]: System.TypeLoadException: Method 'GetTradeSubscription' in type 'ClientWithReconnection' from assembly 'Alpaca.Markets.Extensions, [...] does not have an implementation.

### ISSUE THREAD

**Issue by woaksie** [alpacahq/alpaca-trade-api-csharp#653]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

I just updated all Nuget packages and now I get an error when I run this code.

```cs
var securityKey = new SecretKey(API_KEY, API_SECRET);

ReconnectionParameters reP = new ReconnectionParameters
{
    MaxReconnectionAttempts = 100
};

_streamingClient = Environments.Paper.GetAlpacaStreamingClient(securityKey).WithReconnect(reP);
await _streamingClient.ConnectAndAuthenticateAsync().ConfigureAwait(true);

_streamingClient.OnTradeUpdate += HandleTradeUpdate;

if (Runner.LiveMode)
{
    _streamingData = Environments.Paper.GetAlpacaDataStreamingClient(securityKey).WithReconnect(reP);
    await _streamingData.ConnectAndAuthenticateAsync().ConfigureAwait(true);
}
```

The error is

```cs
System.TypeLoadException: Method 'GetTradeSubscription' in type 'ClientWithReconnection' from assembly 'Alpaca.Markets.Extensions, Version=6.2.0.2, Culture=neutral, PublicKeyToken=16fb7a27ac3b9689' does not have an implementation.
   at Alpaca.Markets.Extensions.AlpacaDataStreamingClientExtensions.WithReconnect(IAlpacaDataStreamingClient client, ReconnectionParameters parameters)
   at TestingAlpaca.AlpacaGateway.SetUpListenerForTrades() in D:\Projects\STOCKS\TestingAlpaca\AlpacaGateway.cs:line 207
```

![image](https://github.com/alpacahq/alpaca-trade-api-csharp/assets/571181/7c68a9b6-2c16-4a7a-9f61-be414dd4e777)

### Expected Behavior

This used to run without an exception.

### Environment

- SDK Version: 6.2.1 and Extensions 6.2.0
- OS (version, bitness): Windows 10 Pro 22H2 64bit
- .NET SDK (version): 4.8.9037.0
- target process .NET version/bitness: 4.8.9037.0 64bit

**Comment by OlegRa** [comment]
@woaksie Please, try to upgrade the Extensions package to version [6.2.1](../releases/tag/ext-6.2.1) available on NuGet - it should solve the problem.

**Comment by woaksie** [comment]
Ok, it is not throwing that exception anymore.
