### ISSUE TITLE
"partial_fill" order status enum parsing issue

### ISSUE THREAD

**Issue by biyimaks** [alpacahq/alpaca-trade-api-csharp#80]
Nuget Package Version: 2.1.4

CoreCLR Version: 4.6.27617.4
**Description: The process was terminated due to an unhandled exception.
Exception Info: Newtonsoft.Json.JsonSerializationException: Error converting value "partial_fill" to type 'Alpaca.Markets.OrderStatus'. Path 'data.event', line 1, position 56. ---> System.ArgumentException: Requested value 'partial_fill' was not found.**
   at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   --- End of inner exception stack trace ---
   at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType)
   at Newtonsoft.Json.Linq.JToken.ToObject[T]()
   **at Alpaca.Markets.SockClient.handleDataReceived(Object sender, DataReceivedEventArgs e)**
   at WebSocket4Net.WebSocket.OnDataReceived(Byte[] data, Int32 offset, Int32 length)
   at SuperSocket.ClientEngine.AuthenticatedStreamTcpSession.ReadAsync()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

**Comment by biyimaks** [comment]
Thanks for merging in the fix to the mainline @OlegRa. When will a new release with the fix be made available ?

**Comment by OlegRa** [comment]
@biyimaks Thank you for reporting this problem! You can get updated version [3.1.1](https://www.nuget.org/packages/Alpaca.Markets/3.1.1) from NuGet - build completed right now. Please, test and close if problem solved.

**Comment by biyimaks** [comment]
I have verified the fix in nuget package version [3.1.1](https://www.nuget.org/packages/Alpaca.Markets/3.1.1). 

Thank you!!!
